cpp/views/auth_views.py
import functools
from flask import Blueprint, url_for, render_template, flash, request, session, g
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect

from cpp import db
from cpp.forms import UserCreateForm, UserLoginForm, UserDeleteForm
from cpp.models import User, User_pcinfo
from cpp.randomcode import giverandomcode

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    form = UserCreateForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            user = User(username=form.username.data,
                        password=generate_password_hash(form.password1.data),
                        nickname=form.nickname.data, codenum=giverandomcode.randomcode)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('이미 존재하는 사용자입니다.')
    return render_template('auth/signup.html', form=form)


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        error = None
        user = User.query.filter_by(username=form.username.data).first()
        if not user:
            error = "존재하지 않는 사용자입니다."
        elif not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('main.homepage'))
        flash(error)
    return render_template('auth/login.html', form=form)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

    #여기서 g.user에 로그인 한 유저의 정보값이 들어감

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:          #로그인 한 상태가 아니라면 첫 페이지로 이동
            return redirect(url_for('main.index'))
        return view(**kwargs)
    return wrapped_view

@bp.route('/mypage/')
@login_required
def mypage():
    user_pcinfo = User_pcinfo.query.filter_by(codenum=g.user.codenum).first()
    return render_template('auth/mypage.html', user_pcinfo=user_pcinfo)


@bp.route('/mypage/quit/', methods=('GET', 'POST'))
def quit():
    form = UserDeleteForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(codenum=form.codenum.data).first()
        if user:
            db.session.delete(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('코드가 일치하지 않습니다.')
    return render_template('auth/quit.html', form=form)

cpp/views/program_views.py
from flask import Blueprint, request, render_template, g
from flask import send_file

from .. import db
from ..models import Cadinfo, Gameinfo, Illustinfo, User_pcinfo, Cpulist, Videocard
from ..views.auth_views import login_required

bp = Blueprint('program', __name__, url_prefix='/program')


@bp.route('/')
def program():
    return render_template('program/program.html')


@bp.route('/cad_list/')
def cad():
    # 입력 파라미터
    kw = request.args.get('kw', type=str, default='')

    cad_list = Cadinfo.query.order_by(Cadinfo.id)
    # 조회
    if kw:
        search = '%%{}%%'.format(kw)
        cad_list = cad_list \
            .filter(Cadinfo.name.ilike(search)   # 질문제목
                    ) \
            .distinct()
    return render_template('program/cad_list.html', cad_list=cad_list, kw=kw)


@bp.route('/cad_list/detail/<int:cad_id>/')
def cad_detail(cad_id):
    cadinfo = Cadinfo.query.get_or_404(cad_id)
    return render_template('program/cad_detail.html', cadinfo=cadinfo)

@bp.route('/game_list/')
def game():
    # 입력 파라미터
    kw = request.args.get('kw', type=str, default='')

    game_list = Gameinfo.query.order_by(Gameinfo.id)
    # 조회
    if kw:
        search = '%%{}%%'.format(kw)
        game_list = game_list \
            .filter(Gameinfo.name.ilike(search)   # 질문제목
                    ) \
            .distinct()
    return render_template('program/game_list.html', game_list=game_list, kw=kw)


@bp.route('/game_list/detail/<int:game_id>/')
def game_detail(game_id):
    gameinfo = Gameinfo.query.get_or_404(game_id)
    return render_template('program/game_detail.html', gameinfo=gameinfo)


@bp.route('/illust_list/')
def illust():
    # 입력 파라미터
    kw = request.args.get('kw', type=str, default='')

    illust_list = Illustinfo.query.order_by(Illustinfo.id)
    # 조회
    if kw:
        search = '%%{}%%'.format(kw)
        illust_list = illust_list \
            .filter(Illustinfo.name.ilike(search)   # 질문제목
                    ) \
            .distinct()
    return render_template('program/illust_list.html', illust_list=illust_list, kw=kw)


@bp.route('/illust_list/detail/<int:illust_id>/')
def illust_detail(illust_id):
    illustinfo = Illustinfo.query.get_or_404(illust_id)
    return render_template('program/illust_detail.html', illustinfo=illustinfo)

@bp.route('/download/')
def download():
    file_name = f"static/exe/programgui.exe"
    return send_file(file_name,
                     mimetype='application/octet-stream',
                     as_attachment=True,
                     attachment_filename='CPP.exe')

# 사양비교

@bp.route('/cad_list/detail/<int:cad_id>/compare/')
@login_required
def cad_compare(cad_id):
    # 프로그램 사양
    cadinfo = Cadinfo.query.get_or_404(cad_id)
    cadcpu = Cpulist.query.filter_by(cpuname=cadinfo.cpu).first()
    cadvideo = Videocard.query.filter_by(vcname=cadinfo.videocard).first()
    cadinfo_os = cadinfo.osversion.split('.')
    cadinfo_os = cadinfo_os[0]
    # 현재 사용자
    user_pcinfo = User_pcinfo.query.filter_by(codenum=g.user.codenum).first()
    usercpu = Cpulist.query.filter_by(cpuname=user_pcinfo.cpu).first()
    # uservideo = Videocard.query.filter_by(vcname=user_pcinfo.graphic1).first()
    a = '%' + user_pcinfo.graphic1 + '%'
    uservideo = Videocard.query.filter(Videocard.vcname.like(a)).first()

    return render_template('program/cad_compare.html', \
                           cadinfo=cadinfo, cadcpu=cadcpu, cadvideo=cadvideo, cadinfo_os=cadinfo_os, \
                           user_pcinfo=user_pcinfo, usercpu=usercpu, uservideo=uservideo)


@bp.route('/game_list/detail/<int:game_id>/compare/')
@login_required
def game_compare(game_id):
    # 프로그램 사양
    gameinfo = Gameinfo.query.get_or_404(game_id)
    gamecpu = Cpulist.query.filter_by(cpuname=gameinfo.cpu).first()
    gamevideo = Videocard.query.filter_by(vcname=gameinfo.videocard).first()
    gameinfo_os = gameinfo.osversion.split('.')
    gameinfo_os = gameinfo_os[0]
    # 현재 사용자
    user_pcinfo = User_pcinfo.query.filter_by(codenum=g.user.codenum).first()
    usercpu = Cpulist.query.filter_by(cpuname=user_pcinfo.cpu).first()
    # uservideo = Videocard.query.filter_by(vcname=user_pcinfo.graphic1).first()
    a = '%' + user_pcinfo.graphic1 + '%'
    uservideo = Videocard.query.filter(Videocard.vcname.like(a)).first()

    return render_template('program/game_compare.html', \
                           gameinfo=gameinfo, gamecpu=gamecpu, gamevideo=gamevideo, gameinfo_os=gameinfo_os, \
                           user_pcinfo=user_pcinfo, usercpu=usercpu, uservideo=uservideo)


@bp.route('/illust_list/detail/<int:illust_id>/compare/')
@login_required
def illust_compare(illust_id):
    # 프로그램 사양
    illustinfo = Illustinfo.query.get_or_404(illust_id)
    illustcpu = Cpulist.query.filter_by(cpuname=illustinfo.cpu).first()
    illustvideo = Videocard.query.filter_by(vcname=illustinfo.videocard).first()
    illustinfo_os = illustinfo.osversion.split('.')
    illustinfo_os = illustinfo_os[0]
    # 현재 사용자
    user_pcinfo = User_pcinfo.query.filter_by(codenum=g.user.codenum).first()
    usercpu = Cpulist.query.filter_by(cpuname=user_pcinfo.cpu).first()
    # uservideo = Videocard.query.filter_by(vcname=user_pcinfo.graphic1).first()
    a = '%' + user_pcinfo.graphic1 + '%'
    uservideo = Videocard.query.filter(Videocard.vcname.like(a)).first()

    return render_template('program/illust_compare.html', \
                           illustinfo=illustinfo, illustvideo=illustvideo, illustcpu=illustcpu, \
                           illustinfo_os=illustinfo_os, user_pcinfo=user_pcinfo, usercpu=usercpu, uservideo=uservideo)

cpp/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
    <!-- cpp CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <!-- template CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/carousel.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/heroes.css') }}">
    <!-- google icon CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <title>CPP</title>
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.scrolly.min.js') }}"></script>
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap/bootstrap.min.js') }}"></script>
<!-- 자바스크립트 Start -->
{% block script %}

{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

cpp/templates/form_errors.html
<!-- 필드오류 -->
{% for field, errors in form.errors.items() %}
<div class="alert alert-danger" role="alert">
    <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
</div>
{% endfor %}
<!-- flash 오류 -->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger" role="alert">
    {{ message }}
</div>
{% endfor %}

cpp/templates/homepage.html
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.min.css') }}">
    <!-- cpp CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <!-- template CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/carousel.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/heroes.css') }}">
    <!-- google icon CSS -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <title>CPP</title>

</head>
<body>

    {% if user_pcinfo.cpu %}            <!-- PC사양 파악 프로그램을 이용하여 DB에 사양을 넣었을 경우 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <a class="navbar-brand" href="{{ url_for('main.homepage') }}">
            <img src="https://www.pngfind.com/pngs/m/489-4892278_c-logo-black-png-transparent-png.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
            CPP
        </a>
        <button class="navbar-toggler ms-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-grow-0 ms-auto" id="navbarNav">
            {% if g.user %}
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.mypage') }}">{{ g.user.username }} 마이페이지</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">(로그아웃)</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('program.program') }}">프로그램</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('question._list') }}">정보공유 게시판</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav">
            </ul>
            {% endif %}
        </div>
    </nav>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1>CPP에 오신것을 환영합니다</h1>
                <p class="lead text-muted">사용하고자 하는 프로그램과의 사양 비교를 하거나 다른 사용자들과 의견을 나눠보세요!</p>
                <p>
                <a href="#main1" class="btn btn-secondary my-2 scrolly">프로그램</a>
                <a href="#main2" class="btn btn-secondary my-2 scrolly">정보 공유 게시판</a>
                </p>
            </div>
        </div>
        <div class="overflow-hidden" style="max-height: 70vh;">
            <div class="container px-5">
                <img src="../static/images/cppmain.png" class="img-fluid border rounded-3 shadow-lg mb-4" alt="Example image" width="700" height="500" loading="lazy">
            </div>
        </div>
    </section>

        <div class="b-example-divider"></div>

    <div id="main1" class="container marketing">
        <div class="p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">
                <a style="color : black; text-decoration : none;" href="{{ url_for('program.program') }}">프로그램 사양 비교 &raquo;</a>
            </h1>
            <p class="fs-5 text-muted">원하는 카테고리를 고르고 프로그램을 선택해주세요.</p>
            <br><br>
            <div class="row">
                <div class="col-lg-4">
                    <img class="bd-placeholder-img rounded-circle" width="300" height="300" src="../static/images/CAD.jpg"></img>

                    <h2>CAD</h2>
                    <p>캐드</p>
                    <p><a class="btn btn-secondary" href="{{ url_for('program.cad') }}">목록 확인 &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-4">
                    <img class="bd-placeholder-img rounded-circle" width="300" height="300" src="../static/images/GAME.png"></img>

                    <h2>GAME</h2>
                    <p>게임</p>
                    <p><a class="btn btn-secondary" href="{{ url_for('program.game') }}">목록 확인 &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
                <div class="col-lg-4">
                    <img class="bd-placeholder-img rounded-circle" width="300" height="300" src="../static/images/ILLUSTRATION.png"></img>

                    <h2>ILLUSTRATOR</h2>
                    <p>일러스트레이터</p>
                    <p><a class="btn btn-secondary" href="{{ url_for('program.illust') }}">목록 확인 &raquo;</a></p>
                </div><!-- /.col-lg-4 -->
            </div><!-- /.row -->
        </div>
    </div>

        <hr class="featurette-divider">

    <div id="main2" class="container marketing py-3">
        <div class="p-3 pb-md-5 mx-auto text-center">
            <h1 class="display-4 fw-normal">
                <a style="color : black; text-decoration : none;" href="{{ url_for('question._list') }}">정보공유 게시판 &raquo;</a>
            </h1>
            <p class="fs-5 text-muted">다양한 사양의 PC를 가진 사용자들과 의견을 나눠 보세요.</p>
            <br>
        </div>

        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3 text-white bg-dark border-secondary">
                        <h4 class="my-0 fw-normal">최신글</h4>
                    </div>
                    <div class="card-body position-relative" style="height: 258px">
                        <h1 class="card-title pricing-card-title"><small class="text-muted fw-light p1">{{ question_list3.first().subject }}</small></h1>
                        <ul class="list-unstyled mt-3 mb-4 p2">
                            <li>{{ question_list3.first().content }}</li>
                        </ul>
                        <a class="w-100 btn btn-lg btn-secondary position-absolute translate-middle boardbottom"
                           href="{{ url_for('question.detail', question_id=question_list3.first().id) }}">해당 게시글로 이동 &raquo;</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3 text-white bg-dark border-secondary">
                        <h4 class="my-0 fw-normal">추천 많은 글</h4>
                    </div>
                    <div class="card-body position-relative" style="height: 258px">
                        <h1 class="card-title pricing-card-title"><small class="text-muted fw-light p1">{{ question_list1.first().subject }}</small></h1>
                        <ul class="list-unstyled mt-3 mb-4 p2">
                            <li>{{ question_list1.first().content }}</li>
                        </ul>
                        <a class="w-100 btn btn-lg btn-secondary position-absolute translate-middle boardbottom"
                           href="{{ url_for('question.detail', question_id=question_list1.first().id) }}">해당 게시글로 이동 &raquo;</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3 text-white bg-dark border-secondary">
                        <h4 class="my-0 fw-normal">댓글 많은 글</h4>
                    </div>
                    <div class="card-body position-relative" style="height: 258px">
                        <h1 class="card-title pricing-card-title"><small class="text-muted fw-light">{{ question_list2.first().subject }}</small></h1>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>{{ question_list2.first().content }}</li>
                        </ul>
                        <a class="w-100 btn btn-lg btn-secondary position-absolute translate-middle boardbottom"
                           href="{{ url_for('question.detail', question_id=question_list2.first().id) }}">해당 게시글로 이동 &raquo;</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br><br><br>

    {% else %}                          <!-- PC사양 파악 프로그램을 이용하여 DB에 사양을 넣지 않았을 경우 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <a class="navbar-brand" href="{{ url_for('main.homepage') }}">
            <img src="https://www.pngfind.com/pngs/m/489-4892278_c-logo-black-png-transparent-png.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
            CPP
        </a>
        <button class="navbar-toggler ms-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-grow-0 ms-auto">
            {% if g.user %}
            <ul class="navbar-nav">
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.mypage') }}">{{ g.user.username }} 마이페이지</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">(로그아웃)</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link disabled" href="{{ url_for('main.homepage') }}">프로그램</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link disabled" href="{{ url_for('question._list') }}">정보공유 게시판</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav">
            </ul>
            {% endif %}
        </div>
    </nav>
    <div class="container col-xl-10 col-xxl-8 px-4 py-5">
        <div class="row align-items-center g-lg-5 py-5">
            <div class="col-md-10 mx-auto col-lg-5">
                <div class="p-4 p-md-5 border rounded-3 bg-light">
                    <h3 style="text-align: center;">PC사양을 등록해주세요!</h3>
                    <div class="form-group form-floating mb-3">
                        <p class="fs-5">웹사이트를 이용하기 위해서는 먼저 PC사양 등록이 필요합니다.<br>아래 버튼을 클릭하여 프로그램을 다운로드 받아주세요.<br>
                        마이페이지에서 본인의 개인 코드를 확인하여 프로그램에서 PC사양을 등록하는데 사용하시면 됩니다!</p>
                    </div>
                    <div class="checkbox mb-3">
                    </div>
                    <hr class="my-4">
                    <small class="text-muted">PC사양 파악 프로그램 다운로드</small>
                    <a href="{{ url_for('program.download') }}" class="btn btn-secondary">다운로드</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- jQuery JS -->
<script src="{{ url_for('static', filename='js/jquery-3.6.0.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.scrolly.min.js') }}"></script>
<!-- Bootstrap JS -->
<script src="{{ url_for('static', filename='bootstrap/bootstrap.min.js') }}"></script>
<!-- 자바스크립트 Start -->
{% block script %}

{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

cpp/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{{ url_for('main.homepage') }}">
        <img src="https://www.pngfind.com/pngs/m/489-4892278_c-logo-black-png-transparent-png.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
        CPP
    </a>
    <button class="navbar-toggler ms-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0 ms-auto" id="navbarNav">
        {% if g.user %}
        <ul class="navbar-nav">
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.mypage') }}">{{ g.user.nickname }} 마이페이지</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">(로그아웃)</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('program.program') }}">프로그램</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{{ url_for('question._list') }}">정보공유 게시판</a>
            </li>
        </ul>
        {% else %}      <!-- 회원가입을 하지 않은 상태에선 뜨지않도록 함 -->
        <ul class="navbar-nav">
        </ul>
        {% endif %}
    </div>
</nav>