cpp/views/program_views.py
from flask import Blueprint, request, render_template, g
from flask import send_file

from .. import db
from ..models import Cadinfo, Gameinfo, Illustinfo, User_pcinfo, Cpulist, Videocard
from ..views.auth_views import login_required

bp = Blueprint('program', __name__, url_prefix='/program')


@bp.route('/')
def program():
    return render_template('program/program.html')


@bp.route('/cad_list/')
def cad():
    # 입력 파라미터
    kw = request.args.get('kw', type=str, default='')

    cad_list = Cadinfo.query.order_by(Cadinfo.id)
    # 조회
    if kw:
        search = '%%{}%%'.format(kw)
        cad_list = cad_list \
            .filter(Cadinfo.name.ilike(search)   # 질문제목
                    ) \
            .distinct()
    return render_template('program/cad_list.html', cad_list=cad_list, kw=kw)


@bp.route('/cad_list/detail/<int:cad_id>/')
def cad_detail(cad_id):
    cadinfo = Cadinfo.query.get_or_404(cad_id)
    return render_template('program/cad_detail.html', cadinfo=cadinfo)

@bp.route('/game_list/')
def game():
    # 입력 파라미터
    kw = request.args.get('kw', type=str, default='')

    game_list = Gameinfo.query.order_by(Gameinfo.id)
    # 조회
    if kw:
        search = '%%{}%%'.format(kw)
        game_list = game_list \
            .filter(Gameinfo.name.ilike(search)   # 질문제목
                    ) \
            .distinct()
    return render_template('program/game_list.html', game_list=game_list, kw=kw)


@bp.route('/game_list/detail/<int:game_id>/')
def game_detail(game_id):
    gameinfo = Gameinfo.query.get_or_404(game_id)
    return render_template('program/game_detail.html', gameinfo=gameinfo)


@bp.route('/illust_list/')
def illust():
    # 입력 파라미터
    kw = request.args.get('kw', type=str, default='')

    illust_list = Illustinfo.query.order_by(Illustinfo.id)
    # 조회
    if kw:
        search = '%%{}%%'.format(kw)
        illust_list = illust_list \
            .filter(Illustinfo.name.ilike(search)   # 질문제목
                    ) \
            .distinct()
    return render_template('program/illust_list.html', illust_list=illust_list, kw=kw)


@bp.route('/illust_list/detail/<int:illust_id>/')
def illust_detail(illust_id):
    illustinfo = Illustinfo.query.get_or_404(illust_id)
    return render_template('program/illust_detail.html', illustinfo=illustinfo)

@bp.route('/download/')
def download():
    file_name = f"static/exe/programgui.exe"
    return send_file(file_name,
                     mimetype='application/octet-stream',
                     as_attachment=True,
                     attachment_filename='CPP.exe')

# 사양비교

@bp.route('/cad_list/detail/<int:cad_id>/compare/')
@login_required
def cad_compare(cad_id):
    # 프로그램 사양
    cadinfo = Cadinfo.query.get_or_404(cad_id)
    cadcpu = Cpulist.query.filter_by(cpuname=cadinfo.cpu).first()
    cadvideo = Videocard.query.filter_by(vcname=cadinfo.videocard).first()
    cadinfo_os = cadinfo.osversion.split('.')
    cadinfo_os = cadinfo_os[0]
    # 현재 사용자
    user_pcinfo = User_pcinfo.query.filter_by(codenum=g.user.codenum).first()
    usercpu = Cpulist.query.filter_by(cpuname=user_pcinfo.cpu).first()
    # uservideo = Videocard.query.filter_by(vcname=user_pcinfo.graphic1).first()
    a = '%' + user_pcinfo.graphic1 + '%'
    uservideo = Videocard.query.filter(Videocard.vcname.like(a)).first()

    return render_template('program/cad_compare.html', \
                           cadinfo=cadinfo, cadcpu=cadcpu, cadvideo=cadvideo, cadinfo_os=cadinfo_os, \
                           user_pcinfo=user_pcinfo, usercpu=usercpu, uservideo=uservideo)


@bp.route('/game_list/detail/<int:game_id>/compare/')
@login_required
def game_compare(game_id):
    # 프로그램 사양
    gameinfo = Gameinfo.query.get_or_404(game_id)
    gamecpu = Cpulist.query.filter_by(cpuname=gameinfo.cpu).first()
    gamevideo = Videocard.query.filter_by(vcname=gameinfo.videocard).first()
    gameinfo_os = gameinfo.osversion.split('.')
    gameinfo_os = gameinfo_os[0]
    # 현재 사용자
    user_pcinfo = User_pcinfo.query.filter_by(codenum=g.user.codenum).first()
    usercpu = Cpulist.query.filter_by(cpuname=user_pcinfo.cpu).first()
    # uservideo = Videocard.query.filter_by(vcname=user_pcinfo.graphic1).first()
    a = '%' + user_pcinfo.graphic1 + '%'
    uservideo = Videocard.query.filter(Videocard.vcname.like(a)).first()

    return render_template('program/game_compare.html', \
                           gameinfo=gameinfo, gamecpu=gamecpu, gamevideo=gamevideo, gameinfo_os=gameinfo_os, \
                           user_pcinfo=user_pcinfo, usercpu=usercpu, uservideo=uservideo)


@bp.route('/illust_list/detail/<int:illust_id>/compare/')
@login_required
def illust_compare(illust_id):
    # 프로그램 사양
    illustinfo = Illustinfo.query.get_or_404(illust_id)
    illustcpu = Cpulist.query.filter_by(cpuname=illustinfo.cpu).first()
    illustvideo = Videocard.query.filter_by(vcname=illustinfo.videocard).first()
    illustinfo_os = illustinfo.osversion.split('.')
    illustinfo_os = illustinfo_os[0]
    # 현재 사용자
    user_pcinfo = User_pcinfo.query.filter_by(codenum=g.user.codenum).first()
    usercpu = Cpulist.query.filter_by(cpuname=user_pcinfo.cpu).first()
    # uservideo = Videocard.query.filter_by(vcname=user_pcinfo.graphic1).first()
    a = '%' + user_pcinfo.graphic1 + '%'
    uservideo = Videocard.query.filter(Videocard.vcname.like(a)).first()

    return render_template('program/illust_compare.html', \
                           illustinfo=illustinfo, illustvideo=illustvideo, illustcpu=illustcpu, \
                           illustinfo_os=illustinfo_os, user_pcinfo=user_pcinfo, usercpu=usercpu, uservideo=uservideo)

cpp/templates/program/cad_compare.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <div class="col-8 mx-auto">
        <h2 class="border-bottom py-2">사양 비교</h2>
        <h2 class="border-bottom py-2">{{ cadinfo.name }} 권장사양</h2>
        <div class="row my-3">
            <div class="col-11">
                <div class="card">
                    <div class="card-body">
                        <div class="card-text">CPU : {{ cadinfo.cpu }}</div>
                        <div class="card-text">VIDEOCARD : {{ cadinfo.videocard }}</div>
                        <div class="card-text">RAM(GB) : {{ cadinfo.ram }}</div>
                        <div class="card-text">Windows OS : {{ cadinfo.osversion }}</div>
                        <div class="card-text">FREE DISK SPACE(MB) : {{ cadinfo.diskspace }}</div>
                    </div>
                </div>
            </div>
        </div>
        <h2 class="border-bottom py-2">{{ g.user.nickname }} 사용자</h2>
        <div class="row my-3">
            <div class="col-11">
                <div class="card">
                    <div class="card-body">
                        <div class="card-text">CPU : {{ user_pcinfo.cpu }}</div>
                        <div class="card-text">VIDEOCARD1 : {{ user_pcinfo.graphic1 }}</div>
                        {% if user_pcinfo.graphic2 %}
                            <div class="card-text">VIDEOCARD2 : {{ user_pcinfo.graphic2 }}</div>
                        {% endif %}

                        <div class="card-text">RAM(GB) : {{ user_pcinfo.ram }}</div>
                        <div class="card-text">Windows OS : {{ user_pcinfo.fullos }}</div>
                        <div class="card-text">FREE DISK SPACE(MB) : C: {{ user_pcinfo.cdisk }} | D: {{ user_pcinfo.ddisk }} | E: {{ user_pcinfo.edisk }} | F: {{ user_pcinfo.fdisk }}</div>
                    </div>
                </div>
            </div>
        </div>
        <h2 class="border-bottom py-2">비교 결과</h2>
       <div class="row my-3">
            <div class="col-11">
                <div class="card">
                    <div class="card-body">
                        <div>           <!-- CPU 비교 -->
                            {% if cadcpu != None %}         <!-- 프로그램 cpu 사양이 있을 때 -->
                                {% if usercpu.score > cadcpu.score %}
                                    <div class="card-text text-primary">CPU : OK!!! / Your CPU score : {{ usercpu.score }} /
                                    CAD's CPU score : {{ cadcpu.score }}</div>
                                {% elif usercpu.score == cadcpu.score %}
                                    <div class="card-text text-primary">CPU : Each other's CPU score is same! / Your CPU score : {{ usercpu.score }} /
                                    CAD's CPU score : {{ cadcpu.score }}</div>
                                {% else %}
                                    <div class="card-text text-danger">CPU : NO!!! / Your CPU score : {{ usercpu.score }} /
                                    CAD's CPU score : {{ cadcpu.score }}</div>
                                {% endif %}
                            {% else %}                      <!-- 프로그램 cpu 사양이 비었을 때 -->
                                <div class="card-text text-primary">CPU : OK!!!</div>
                            {% endif %}
                        </div>
                        <hr/>
                        <div>         <!-- 그래픽카드 비교 -->
                            {% if (cadvideo.score) and (uservideo.score) %}         <!-- 프로그램 videocard 사양이 있을 때 -->
                                {% if uservideo.score > cadvideo.score %}
                                    <div class="card-text text-primary">VIDEOCARD : OK!!! / Your Videocard score : {{ uservideo.score }} /
                                    CAD's Videocard score : {{ cadvideo.score }}</div>
                                {% elif uservideo.score == cadvideo.score %}
                                    <div class="card-text text-primary">VIDEOCARD : Each other's Videocard score is same! / Your Videocard score : {{ user_video.score }} /
                                    CAD's Videocard score : {{ cadvideo.score }}</div>
                                {% else %}
                                    <div class="card-text text-danger">VIDEOCARD : NO!!! / Your Videocard score : {{ uservideo.score }} /
                                    CAD's Videocard score : {{ cadvideo.score }}</div>
                                {% endif %}
                            {% elif (uservideo.score == NONE) and (cadvideo.score) %}                      <!-- 프로그램 videocard 사양이 비었을 때 -->
                                <div class="card-text text-danger">YOUR VideoCard is not in our database!</div>
                            {% elif (cadvideo.score == NONE) and (uservideo.score) %}
                                <div class="card-text text-primary">VIDEOCARD : OK!!!</div>
                            {% else %}
                                <div class="card-text text-primary">VIDEOCARD : OK!!!</div>
                            {% endif %}
                        </div>
                        <hr/>
                        <div>           <!-- RAM 비교 -->
                            {% if cadinfo.ram %}         <!-- 프로그램 RAM 사양이 있을 때 -->
                                {% if user_pcinfo.ram > cadinfo.ram %}
                                    <div class="card-text text-primary">RAM : OK!!!</div>
                                {% elif user_pcinfo.ram == cadinfo.ram %}
                                    <div class="card-text text-primary">RAM : Each other's RAM size is same!</div>
                                {% else %}
                                    <div class="card-text text-danger">RAM : NO!!!</div>
                                {% endif %}
                            {% else %}
                                <div class="card-text text-primary">RAM : OK!!!</div>
                            {% endif %}
                        </div>
                        <hr/>
                        <div>            <!-- WINDOWS 버전 비교 /  XP<Vista<7<8<10 -->
                            {% if cadinfo_os %}
                                {% if cadinfo_os == 'XP' %}
                                    <div class="card-text text-primary">OS : OK!!!</div>
                                {% elif cadinfo_os == 'Vista' %}
                                    {% if user_pcinfo.os == 'XP' %}
                                        <div class="card-text text-danger">OS : NO!!!</div>
                                    {% else %}
                                        <div class="card-text text-primary">OS : OK!!!</div>
                                    {% endif %}
                                {% elif cadinfo_os == '7' %}
                                    {% if ((user_pcinfo.os == 'Vista') or (user_pcinfo.os == 'XP')) %}
                                        <div class="card-text text-danger">OS : NO!!!</div>
                                    {% else %}
                                        <div class="card-text text-primary">OS : OK!!!</div>
                                    {% endif %}
                                {% elif cadinfo_os == '8' %}
                                    {% if ((user_pcinfo.os == 'Vista') or (user_pcinfo.os == 'XP') or (user_pcinfo.os == '7')) %}
                                        <div class="card-text text-danger">OS : NO!!!</div>
                                    {% else %}
                                        <div class="card-text text-primary">OS : OK!!!</div>
                                    {% endif %}
                                {% elif cadinfo_os == '9' %}
                                    {% if ((user_pcinfo.os == '9') or (user_pcinfo.os == '10')) %}
                                        <div class="card-text text-primary">OS : OK!!!</div>
                                    {% else %}
                                        <div class="card-text text-danger">OS : NO!!!</div>
                                    {% endif %}
                                {% elif cadinfo_os == '10' %}
                                    {% if user_pcinfo.os == '10' %}
                                        <div class="card-text text-primary">OS : OK!!!</div>
                                    {% else %}
                                        <div class="card-text text-danger">OS : NO!!!</div>
                                    {% endif %}
                                {% endif %}
                            {% else %}
                                    <div class="card-text text-danger">OS : NO!!!</div>
                            {% endif %}
                        </div>
                        <hr/>
                        <div>          <!-- FREE DISK SPACE 용량 비교 -->
                            {% if cadinfo.diskspace %}
                                {% if user_pcinfo.cdisk >= cadinfo.diskspace %}
                                    <div class="card-text text-primary">C_disk : OK!!!</div>
                                {% else %}
                                    <div class="card-text text-danger">C_disk : NO!!!</div>
                                {% endif %}
                                {% if user_pcinfo.ddisk >= cadinfo.diskspace %}
                                    <div class="card-text text-primary">D_disk : OK!!!</div>
                                {% else %}
                                    <div class="card-text text-danger">D_disk : NO!!!</div>
                                {% endif %}
                                {% if user_pcinfo.edisk >= cadinfo.diskspace %}
                                    <div class="card-text text-primary">E_disk : OK!!!</div>
                                {% else %}
                                    <div class="card-text text-danger">E_disk : NO!!!</div>
                                {% endif %}
                                {% if user_pcinfo.fdisk >= cadinfo.diskspace %}
                                    <div class="card-text text-primary">F_disk : OK!!!</div>
                                {% else %}
                                    <div class="card-text text-danger">F_disk : NO!!!</div>
                                {% endif %}
                            {% else %}
                                <div class="card-text text-primary">ALL_disk : OK!!!</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


{% endblock %}
{% block script %}

{% endblock %}

cpp/templates/program/cad_detail.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <div class="col-8 mx-auto">
        <h2 class="border-bottom py-2">{{ cadinfo.name }}</h2>
        <div class="row my-3">
            <div class="col-11">
                <div class="card">
                    <div class="card-body">
                        <div class="card-text">CPU : {{ cadinfo.cpu }}</div>
                        <div class="card-text">VIDEOCARD : {{ cadinfo.videocard }}</div>
                        <div class="card-text">RAM(GB) : {{ cadinfo.ram }}</div>
                        <div class="card-text">Windows OS : {{ cadinfo.osversion }}</div>
                        <div class="card-text">FREE DISK SPACE(MB) : {{ cadinfo.diskspace }}</div>
                    </div>
                </div>
            </div>
        </div>
        <a href="{{ url_for('program.cad_compare', cad_id=cadinfo.id, cad_cpu=cadinfo.cpu) }}" class="btn btn-secondary">내 PC와 비교하기</a>
    </div>
</div>
{% endblock %}

cpp/templates/program/cad_list.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <div class="col-8 mx-auto">
        <div class="row justify-content-end my-3">
            <div class="col-4 input-group">
                <input type="text" class="form-control kw" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
        <table class="table table-hover table-bordered">
            <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th style="width:50%">제목</th>
            </tr>
            </thead>
            <tbody>
            {% if cad_list %}
            {% for cad in cad_list %}
            <tr class="text-center">
                <td>{{ loop.index }}</td>
                <td class="text-left">
                    <a href="{{ url_for('program.cad_detail', cad_id=cad.id) }}">{{ cad.name }}</a>
                </td>
            </tr>
            {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
</div>

<form id="searchForm" method="get" action="{{ url_for('program.cad') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>

{% endblock %}

cpp/templates/program/game_detail.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <div class="col-8 mx-auto">
        <h2 class="border-bottom py-2">{{ gameinfo.name }}</h2>
        <div class="row my-3">
            <div class="col-11">
                <div class="card">
                    <div class="card-body">
                        <div class="card-text">CPU : {{ gameinfo.cpu }}</div>
                        <div class="card-text">VIDEOCARD : {{ gameinfo.videocard }}</div>
                        <div class="card-text">RAM(GB) : {{ gameinfo.ram }}</div>
                        <div class="card-text">Windows OS : {{ gameinfo.osversion }}</div>
                        <div class="card-text">FREE DISK SPACE(MB) : {{ gameinfo.diskspace }}</div>
                    </div>
                </div>
            </div>
        </div>
        <a href="{{ url_for('program.game_compare', game_id=gameinfo.id, game_cpu=gameinfo.cpu) }}" class="btn btn-secondary">내 PC와 비교하기</a>
    </div>
</div>
{% endblock %}

cpp/templates/program/game_list.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <div class="col-8 mx-auto">
        <div class="row justify-content-end my-3">
            <div class="col-4 input-group">
                <input type="text" class="form-control kw" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
        <table class="table table-hover table-bordered">
            <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th style="width:50%">제목</th>
            </tr>
            </thead>
            <tbody>
            {% if game_list %}
            {% for game in game_list %}
            <tr class="text-center">
                <td>{{ loop.index }}</td>
                <td class="text-left">
                    <a href="{{ url_for('program.game_detail', game_id=game.id) }}">{{ game.name }}</a>
                </td>
            </tr>
            {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
</div>

<form id="searchForm" method="get" action="{{ url_for('program.game') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>

{% endblock %}

cpp/templates/program/illust_detail.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <div class="col-8 mx-auto">
        <h2 class="border-bottom py-2">{{ illustinfo.name }}</h2>
        <div class="row my-3">
            <div class="col-11">
                <div class="card">
                    <div class="card-body">
                        <div class="card-text">CPU : {{ illustinfo.cpu }}</div>
                        <div class="card-text">VIDEOCARD : {{ illustinfo.videocard }}</div>
                        <div class="card-text">RAM(GB) : {{ illustinfo.ram }}</div>
                        <div class="card-text">Windows OS : {{ illustinfo.osversion }}</div>
                        <div class="card-text">FREE DISK SPACE(MB) : {{ illustinfo.diskspace }}</div>
                    </div>
                </div>
            </div>
        </div>
        <a href="{{ url_for('program.illust_compare', illust_id=illustinfo.id, illust_cpu=illustinfo.cpu) }}" class="btn btn-secondary">내 PC와 비교하기</a>
    </div>
</div>
{% endblock %}

cpp/templates/program/illust_list.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<div class="container my-3">
    <div class="col-8 mx-auto">
        <div class="row justify-content-end my-3">
            <div class="col-4 input-group">
                <input type="text" class="form-control kw" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
        <table class="table table-hover table-bordered">
            <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th style="width:50%">제목</th>
            </tr>
            </thead>
            <tbody>
            {% if illust_list %}
            {% for illust in illust_list %}
            <tr class="text-center">
                <td>{{ loop.index }}</td>
                <td class="text-left">
                    <a href="{{ url_for('program.illust_detail', illust_id=illust.id) }}">{{ illust.name }}</a>
                </td>
            </tr>
            {% endfor %}
            {% endif %}
            </tbody>
        </table>
    </div>
</div>

<form id="searchForm" method="get" action="{{ url_for('program.illust') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>

{% endblock %}

cpp/templates/program/program.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="col-12 mx-auto">
            <hr class="featurette-divider">
        <div id="main1" class="container marketing">
            <div class="p-3 pb-md-4 mx-auto text-center">
                <h1 class="display-4 fw-normal">프로그램 사양 비교</h1>
                <p class="fs-5 text-muted">원하는 카테고리를 고르고 프로그램을 선택해주세요.</p>
                <div class="row">
                    <div class="col-lg-4">
                        <img class="bd-placeholder-img rounded-circle" width="300" height="300" src="../static/images/CAD.jpg"></img>

                        <h2>CAD</h2>
                        <p>캐드</p>
                        <p><a class="btn btn-secondary" href="{{ url_for('program.cad') }}">목록 확인 &raquo;</a></p>
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-4">
                        <img class="bd-placeholder-img rounded-circle" width="300" height="300" src="../static/images/GAME.png"></img>

                        <h2>GAME</h2>
                        <p>게임</p>
                        <p><a class="btn btn-secondary" href="{{ url_for('program.game') }}">목록 확인 &raquo;</a></p>
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-4">
                        <img class="bd-placeholder-img rounded-circle" width="300" height="300" src="../static/images/ILLUSTRATION.png"></img>

                        <h2>ILLUSTRATOR</h2>
                        <p>일러스트레이터</p>
                        <p><a class="btn btn-secondary" href="{{ url_for('program.illust') }}">목록 확인 &raquo;</a></p>
                    </div><!-- /.col-lg-4 -->
                </div><!-- /.row -->
            </div>
        </div>
            <hr class="featurette-divider">
        <div>
            <a href="{{ url_for('main.homepage') }}" class="btn btn-secondary col-2">&laquo; 메인으로</a>
        </div>
    </div>
</div>
{% endblock %}